name: Metrics
on:
  schedule:
    - cron: "0 0-23/4 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: 🦑 Personal metrics (left)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: header

          # Templete
          template: classic

          # Isometric commit calendar
          plugin_isocalendar: yes
          
          # Most used languages
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, gnuplot, vue, scala, ejs
          plugin_languages_details: lines, percentage
          plugin_languages_limit: 10
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes

          # Starred topics
          plugin_topics: yes
          plugin_topics_sort: stars    # Sort by most starred topics
          plugin_topics_mode: mastered # Display icons instead of labels
          plugin_topics_limit: 0       # Disable limitations

          # Notable
          plugin_notable: yes
          plugin_notable_repositories: no

          # Order
          config_order: base.header, isocalendar, languages, notable, topics